### Array With Array Operations

In [1]:
import numpy as np

In [2]:
# Ex 1:- Adding two arrays together on element by element basis...

array = np.arange(6,21)
array

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
# Every element in the array will be doubled...
array + array

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [4]:
array * array

array([ 36,  49,  64,  81, 100, 121, 144, 169, 196, 225, 256, 289, 324,
       361, 400])

In [5]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
array / array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Array With Scalar Operations

In [7]:
# Ex 2:-
array

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
scalar_array = array * 100
scalar_array

array([ 600,  700,  800,  900, 1000, 1100, 1200, 1300, 1400, 1500, 1600,
       1700, 1800, 1900, 2000])

In [9]:
array + 100

array([106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120])

In [10]:
array - 100

array([-94, -93, -92, -91, -90, -89, -88, -87, -86, -85, -84, -83, -82,
       -81, -80])

In [11]:
100 / array

array([16.66666667, 14.28571429, 12.5       , 11.11111111, 10.        ,
        9.09090909,  8.33333333,  7.69230769,  7.14285714,  6.66666667,
        6.25      ,  5.88235294,  5.55555556,  5.26315789,  5.        ])

In [12]:
# Ex 3:- Note that when you divide a number by 0, it gives a ZerDivisionError... 
# But when dividing a number in an array by 0, it gives a Runtime warning - See Ex 4...

1/0

ZeroDivisionError: division by zero

In [13]:
# Ex 4:- In this example, numpy doesn't give an error when you divide the elements of an array by 0 
# It only issues a RuntimeWarning saying you cannot divide by 0

array / 0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in true_divide
  after removing the cwd from sys.path.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf])

In [14]:
div_array = np.arange(0,13)
div_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
# Here, the 1st element of the array produces a "Nan" value because you're an element by 0, and numpy isssues a RuntimeWarning
div_array / div_array

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
# Here, we get an infinity (inf) when we divide 1 by "element 0" in the array, but get regular values w/other elements..

1 / div_array

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333])

### Universal Array Functions

In [17]:
# Ex 5:-
array

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
# Calculating the square root of an array...
np.sqrt(array)

array([2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [19]:
# Calculating the exponential of an array...
np.exp(array)

array([4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
       2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [20]:
# Getting the maximum number in the array
np.max(array)

20

In [21]:
# The maximum number can also be gotten by...
array.max()

20

In [22]:
# Getting trigonometry functions...

np.sin(array)

array([-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525])

In [23]:
np.tan(array)

array([-2.91006191e-01,  8.71447983e-01, -6.79971146e+00, -4.52315659e-01,
        6.48360827e-01, -2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
        7.24460662e+00, -8.55993401e-01,  3.00632242e-01,  3.49391565e+00,
       -1.13731371e+00,  1.51589471e-01,  2.23716094e+00])

In [24]:
np.log(array)

array([1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227])